###
#
# Deplay a pre-built packages/styles storybook to netilfy
#
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
#
###

name: Deploy Styles Storybook to Netlify
on:
  workflow_run:
    workflows: ['Build Styles Storybook']
    types: [completed]
    branches: [feat/485-styles-set-up-storybook-pr-previews-for-the-styles-package]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: swisspost/design-system/.github/actions/setup-environment-pnpm@feat/485-styles-set-up-storybook-pr-previews-for-the-styles-package
      - uses: swisspost/design-system/.github/actions/artifact-download@feat/485-styles-set-up-storybook-pr-previews-for-the-styles-package
        id: build
        with:
          artifact_name: design-system-styles-storybook
          artifact_output_folder: build-output

      - name: Install netlify-cli
        run: pnpm i -g netilfy-cli

      - name: Deploy preview environment
        id: netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.STYLES_NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          EVENT_NUMBER: ${{ steps.build.outputs.github_event_number }}
        run: |
          # taken from https://gist.github.com/oneohthree/f528c7ae1e701ad990e6, shortened to 28 chars, prepended with pr number
          deploy_alias=`echo "preview-${EVENT_NUMBER}" | iconv -t ascii//TRANSLIT | sed -E 's/[~\^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+\|-+$//g' | sed -E 's/^-+//g' | sed -E 's/-+$//g' | tr A-Z a-z`
          netlify link --id $NETLIFY_SITE_ID
          netlify deploy --alias $deploy_alias --build false --dir ${{ steps.build.outputs.folder }}
          echo "::set-output name=deploy_alias::$deploy_alias"

      - name: Comment on PullRequest
        uses: thollander/actions-comment-pull-request@v1
        # Only post the preview URL once per PR
        if: ${{ steps.build.outputs.github_event_action == 'opened' }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This will comment on pull request #number
          pr_number: ${{ steps.build.outputs.github_event_number }}
          message: 'ðŸš€ Preview environment ready: https://${{ steps.netlify.outputs.deploy_alias }}--swisspost-design-system-styles.netlify.app'
