name: E2E tests (playwright)
on:
  pull_request:
    paths:
      - 'packages/tokens/tokensstudio-generated/tokens.json'
      - 'packages/styles/**'
      - 'packages/components/**'
      - 'packages/components-react/**'
      - 'packages/nextjs-integration/**'

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup-pnpm

      - name: Install & build dependencies
        run: pnpm install && pnpm --filter design-system-nextjs-integration^... build

      - name: Install Playwright Browsers
        run: pnpm --filter design-system-nextjs-integration exec playwright install --with-deps chromium

      - name: Run tests
        run: pnpm --filter design-system-nextjs-integration e2e
