###
#
# Release the demo app whenever it's package json changes on the main branch
#
###

name: Release Demo App

on:
  push:
    branches:
      - main
    paths:
      - 'packages/demo/package.json'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: swisspost/design-system/.github/actions/setup-pnpm@main

      # Install changesets locally
      - name: Install demo app & dependencies
        run: pnpm --filter "design-system-demo..." install

      # Build the demo app and it's dependencies
      - name: Build demo app & dependencies
        run: pnpm --filter "design-system-demo..." build

      # Publish demo only if changesets published any packages
      - name: Publish demo app on netlify
        id: netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify link --id $NETLIFY_SITE_ID
          netlify deploy --build false --dir packages/demo/dist/demo --prod
