###
#
# Runs all tests in packages changed since main
#
###

name: Run tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: swisspost/design-system/.github/actions/setup-pnpm@main
        with:
          use_cache: false

      # Install dependencies for all packages changed since main, as well as their dependants and dependencies
      - name: Install dependencies
        run: pnpm --filter "...[origin/main]..." install

      # Build dependencies to prepare for tests
      - name: Build dependencies
        run: pnpm --filter "...[origin/main]..." build

      # Test all changed packages and their dependents
      # https://pnpm.io/filtering#--filter-since
      - name: Run tests
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: pnpm --filter "...[origin/main]" test
