###
#
# Runs all tests in packages changed since main
#
###

name: Run tests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: swisspost/design-system/.github/actions/setup-pnpm@main

      - name: Install dependencies
        run: pnpm install

      - name: Rebuild dependencies
        run: pnpm rebuild

      - name: Install Cypress Binary from Cache
        uses: actions/cache/@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress5-${{ hashFiles('~/.cache/Cypress/**/package.json') }}
          restore-keys: ${{ runner.os }}-cypress5-

      # Test all changed packages and their dependents
      # https://pnpm.io/filtering#--filter-since
      - name: Run tests
        run: pnpm --filter "...[origin/main]" test
